# Generated by Django 3.0.6 on 2020-05-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Something', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='where',
            field=models.CharField(max_length=255),
        ),
    ]
