# Generated by Django 3.0.6 on 2020-05-14 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_to_Event_rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.IntegerField(choices=[(1, 'Admin'), (2, 'Readwrite'), (3, 'Read')])),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Event')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profile')),
            ],
        ),
    ]
